name: Bug report
description: Report a bug with the godot-cpp template
body:

- type: markdown
  attributes:
    value: |
      - Write a descriptive issue title above.
      - Search [open](https://github.com/dmrokan/gdmatplot/issues) and [closed](https://github.com/dmrokan/gdmatplot/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported.
- type: input
  attributes:
    label: Godot version
    description: >
      Specify the Git commit hash of your Godot build.
    placeholder: v4.2.2.stable.official [15073afe3]
  validations:
    required: true

- type: input
  attributes:
    label: godot-cpp version
    description: >
      If you build from source, specify the Git commit hash of the godot-cpp submodule in your project. You can run `git status` inside the folder to check it.
    placeholder: godot-4.2.2-stable [98c143a48]
  validations:
    required: false

- type: input
  attributes:
    label: System information
    description: |
      Specify the OS version.
    placeholder: Ubuntu 22.04
  validations:
    required: true

- type: textarea
  attributes:
    label: Issue description
    description: |
      Describe your issue briefly. What doesn't work, and how do you expect it to work instead?
      You can include images or videos with drag and drop, and format code blocks or logs with <code>```</code> tags.
  validations:
    required: true