name: Builds

on:
  push:
    branches: [ main, workflow-test ]
    tags:
      - "v*"

env:
  LIBNAME: libgdmatplot

jobs:
  build:
    runs-on: ${{matrix.os}}
    name: ${{matrix.name}}
    strategy:
      fail-fast: false
      matrix:
        include:
          - identifier: debug-build
            os: ubuntu-24.04
            name: Debug
            runner: ubuntu-24.04
            target: template_debug
            platform: linux
            arch: x86_64
          - identifier: release-build
            os: ubuntu-24.04
            name: Release
            runner: ubuntu-24.04
            target: template_release
            platform: linux
            arch: x86_64

    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Set up SCons
        shell: bash
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install scons==4.7.0
          scons --version

      - name: Linux dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qqq build-essential pkg-config mingw-w64

      - name: Compile gnuplot shared lib
        shell: sh
        run: |
          scons -f SConscript platform='windows'

      - name: Compile godot-cpp
        shell: sh
        run: |
          scons target='${{ matrix.target }}' platform='windows' arch='${{ matrix.arch }}'
        working-directory: godot-cpp

      - name: Compile Extension
        shell: sh
        run: |
          scons target='${{ matrix.target }}' platform='windows' arch='${{ matrix.arch }}'

      - name: Compile gnuplot shared lib
        shell: sh
        run: |
          scons -f SConscript platform='linux'

      - name: Compile godot-cpp
        shell: sh
        run: |
          scons target='${{ matrix.target }}' platform='linux' arch='${{ matrix.arch }}'
        working-directory: godot-cpp

      - name: Compile Extension
        shell: sh
        run: |
          scons target='${{ matrix.target }}' platform='linux' arch='${{ matrix.arch }}'

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}
          path: |
            ${{ github.workspace }}/demo/addons

  release:
    name: Release
    runs-on: "ubuntu-latest"
    needs: [ build ]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download Artifacts
        id: download
        uses: actions/download-artifact@v3
      - name: Copy extension into demo
        run: cp -fr "${{ github.event.repository.name }}/${{ github.event.repository.name }}" demo/addons && cp -rf demo/addons demo3d/
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: '${{ github.event.repository.name }}.zip'
          directory: '${{ github.event.repository.name }}'
      - name: Demo release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'demo.zip'
          path: 'demo'
      - name: Demo3D release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'demo3d.zip'
          path: 'demo3d'
      - name: Create and upload asset
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "${{ github.event.repository.name }}/${{ github.event.repository.name }}.zip,demo.zip,demo3d.zip"
          omitNameDuringUpdate: true
          omitBodyDuringUpdate: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifactErrorsFailBuild: true
